//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSphere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.LoyaltyTransactions = new HashSet<LoyaltyTransaction>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public int Quantity { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> DiscountApplied { get; set; }
        public decimal FinalAmount { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<bool> CheckInStatus { get; set; }
        public string Notes { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyTransaction> LoyaltyTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
