//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSphere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> Points { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual User User { get; set; }
    }
}
