//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSphere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public string TicketNumber { get; set; }
        public string QRCodeImage { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
